name: Clear Symfony cache (CLI)
description: Clear Symfony cache using PHP CLI

inputs:
  host:
    required: true
  user:
    required: true
  port:
    required: true
  path:
    required: true
  php-path:
    required: true

runs:
  using: composite
  steps:
    - name: Clear Symfony cache
      shell: bash
      run: |
        ssh -p "${{ inputs.port }}" "${{ inputs.user }}@${{ inputs.host }}" \
        "cd '${{ inputs.path }}' && \
        ${{ inputs.php-path }} bin/console cache:clear --env=prod"