name: Clear Symfony cache (Docker)
description: Clear Symfony cache inside Docker container

inputs:
  host:
    required: true
  user:
    required: true
  port:
    required: true
  container:
    required: true

runs:
  using: composite
  steps:
    - name: Clear Symfony cache
      shell: bash
      run: |
        ssh -p "${{ inputs.port }}" "${{ inputs.user }}@${{ inputs.host }}" \
        "docker exec ${{ inputs.container }} php bin/console cache:clear --env=prod"